# Generated by Django 4.2.1 on 2023-07-23 12:09

import auth_views.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0006_alter_user_options_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', auth_views.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
