# Generated by Django 4.2.1 on 2023-07-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0007_alter_user_managers_user_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
    ]
