# Generated by Django 4.2.1 on 2023-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0010_remove_userprofile_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
