# Generated by Django 4.2.1 on 2023-07-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(blank=True, choices=[('0-500', '0-500'), ('500-1000', '500-1000'), ('1000+', '1000+')], max_length=15, null=True),
        ),
    ]
