# Generated by Django 4.2.1 on 2023-07-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0003_delete_landlord_delete_user'),
        ('auth_views', '0013_userprofile_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
