# Generated by Django 4.2.1 on 2023-07-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0017_alter_profile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[(None, ''), ('STUDIO', 'Studio'), ('APPARTMENT', 'Appartment'), ('SINGLE_ROOM', 'Single Room')], max_length=11, null=True),
        ),
    ]
