# Generated by Django 4.2.1 on 2023-07-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0021_alter_profile_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.CharField(choices=[(None, 'Other'), ('0 LV - 500 LV', '0 LV - 500 LV'), ('500 LV -1000 LV', '500 LV - 1000 LV'), ('1000+ LV', '1000+ LV')], max_length=15, null=True),
        ),
    ]
