# Generated by Django 4.2.1 on 2023-07-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0023_alter_profile_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.CharField(choices=[(None, 'Other'), ('0 Lv. - 500 Lv.', '0 Lv. - 500 Lv.'), ('500 Lv. - 1000 Lv.', '500 Lv. - 1000 Lv.'), ('1000+ Lv.', '1000+ Lv.')], max_length=18, null=True),
        ),
    ]
