# Generated by Django 4.2.1 on 2023-07-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0003_delete_landlord_delete_user'),
        ('auth_views', '0026_landlordprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='offerings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_view.property'),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[(None, 'Other'), ('STUDIO', 'Studio'), ('APPARTMENT', 'Appartment'), ('SINGLE_ROOM', 'Single Room')], max_length=11),
        ),
    ]
