# Generated by Django 4.2.1 on 2023-07-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0027_landlordprofile_first_name_landlordprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord')], default='TENANT', max_length=11),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='type',
            field=models.CharField(choices=[('PRIVATE_OWNER', 'Private Owner'), ('COMPANY', 'Company')], default='PRIVATE_OWNER', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.CharField(choices=[(None, ''), ('0 Lv. - 500 Lv.', '0 Lv. - 500 Lv.'), ('500 Lv. - 1000 Lv.', '500 Lv. - 1000 Lv.'), ('1000+ Lv.', '1000+ Lv.')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[(None, ''), ('STUDIO', 'Studio'), ('APPARTMENT', 'Appartment'), ('SINGLE_ROOM', 'Single Room')], max_length=11),
        ),
    ]
