# Generated by Django 4.2.1 on 2023-07-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0028_user_type_alter_landlordprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
