# Generated by Django 4.2.1 on 2023-07-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0029_landlordprofile_is_finished_profile_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
