# Generated by Django 4.2.1 on 2023-07-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0030_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
