# Generated by Django 4.2.1 on 2023-07-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0032_user_profile_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlordprofile',
            old_name='is_finished',
            new_name='profile_finished',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_finished',
            new_name='profile_finished',
        ),
    ]
