# Generated by Django 4.2.1 on 2023-07-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0033_rename_is_finished_landlordprofile_profile_finished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='offerings',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_properties',
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('APPARTMENT', 'Appartment'), ('SINGLE_ROOM', 'Single Room')], max_length=11),
        ),
    ]
