# Generated by Django 4.2.1 on 2023-07-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0034_remove_landlordprofile_offerings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlordprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
