# Generated by Django 4.2.1 on 2023-08-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0036_landlordprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('APPARTMENT', 'Appartment'), ('SINGLE ROOM', 'Single Room')], default='STUDIO', max_length=11),
        ),
    ]
