# Generated by Django 4.2.1 on 2023-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0037_alter_profile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='TENANT', max_length=11),
        ),
    ]
