# Generated by Django 4.2.1 on 2023-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0040_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord')], default='TENANT', max_length=11),
        ),
    ]
