# Generated by Django 4.2.1 on 2023-08-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_picture_remove_property_landlord_alter_property_town_and_more'),
        ('auth_views', '0042_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='properties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
