# Generated by Django 4.2.1 on 2023-08-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_pictures'),
        ('auth_views', '0043_landlordprofile_properties_profile_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='properties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
