# Generated by Django 4.2.1 on 2023-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0045_remove_landlordprofile_properties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='location',
            field=models.TextField(choices=[('SOFIA', 'Sofia'), ('PLOVDIV', 'Plovdiv'), ('VARNA', 'Varna'), ('BURGAS', 'Burgas'), ('RUSE', 'Ruse'), ('STARA ZAGORA', 'Stara Zagora'), ('PLEVEN', 'Pleven'), ('SLIVEN', 'Sliven'), ('DOBRICH', 'Dobrich'), ('SHUMEN', 'Shumen'), ('PERNIK', 'Pernik'), ('HASKOVO', 'Haskovo'), ('YAMBOL', 'Yambol'), ('Pazardzhik', 'Pazardzhik'), ('BLAGOEVGRAD', 'Blagoevgrad'), ('VELIKO TARNOVO', 'Veliko Tarnovo'), ('VIDIN', 'Vidin'), ('MONTANA', 'Montana'), ('LOVECH', 'Lovech'), ('RAZGRAD', 'Razgrad')], default='SOFIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='type',
            field=models.CharField(choices=[('Private Owner', 'PRIVATE_OWNER'), ('Company', 'COMPANY')], default='Private Owner', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_occupation',
            field=models.CharField(choices=[('Other', 'OTHER'), ('Student', 'STUDENT'), ('Worker', 'WORKER')], default='Other', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(choices=[('SOFIA', 'Sofia'), ('PLOVDIV', 'Plovdiv'), ('VARNA', 'Varna'), ('BURGAS', 'Burgas'), ('RUSE', 'Ruse'), ('STARA ZAGORA', 'Stara Zagora'), ('PLEVEN', 'Pleven'), ('SLIVEN', 'Sliven'), ('DOBRICH', 'Dobrich'), ('SHUMEN', 'Shumen'), ('PERNIK', 'Pernik'), ('HASKOVO', 'Haskovo'), ('YAMBOL', 'Yambol'), ('Pazardzhik', 'Pazardzhik'), ('BLAGOEVGRAD', 'Blagoevgrad'), ('VELIKO TARNOVO', 'Veliko Tarnovo'), ('VIDIN', 'Vidin'), ('MONTANA', 'Montana'), ('LOVECH', 'Lovech'), ('RAZGRAD', 'Razgrad')], default='SOFIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('Studio', 'STUDIO'), ('Appartment', 'APPARTMENT'), ('Single Room', 'SINGLE ROOM')], default='Studio', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Tenant', 'TENANT'), ('Landlord', 'LANDLORD')], default='Tenant', max_length=11),
        ),
    ]
