# Generated by Django 4.2.1 on 2023-07-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=20)),
                ('landlord', models.TextField()),
                ('street', models.TextField()),
                ('street_number', models.IntegerField()),
                ('floor', models.IntegerField(blank=True, default=0, null=True)),
                ('area_postcode', models.IntegerField()),
                ('availability', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('furnished', models.BooleanField()),
                ('utilities_included', models.BooleanField()),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_view.town')),
            ],
        ),
    ]
