# Generated by Django 4.2.1 on 2023-07-06 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('type', models.CharField(choices=[('STUDIO', 'Studio'), ('APPARTMENT', 'Appartment'), ('SINGLE_ROOM', 'Single Room')], max_length=11)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=20)),
                ('landlord', models.TextField()),
                ('street', models.TextField()),
                ('street_number', models.IntegerField()),
                ('floor', models.IntegerField(blank=True, default=0, null=True)),
                ('area_postcode', models.IntegerField()),
                ('availability', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('furnished', models.BooleanField()),
                ('utilities_included', models.BooleanField()),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_view.town')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
