# Generated by Django 4.2.1 on 2023-08-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
