# Generated by Django 4.2.1 on 2023-08-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_views', '0045_remove_landlordprofile_properties_and_more'),
        ('user_profile', '0002_delete_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_views.profile')),
            ],
        ),
    ]
