# Generated by Django 4.2.1 on 2023-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='town',
            field=models.CharField(blank=True, choices=[('SOFIA', 'Sofia'), ('PLOVDIV', 'Plovdiv'), ('VARNA', 'Varna'), ('BURGAS', 'Burgas'), ('RUSE', 'Ruse'), ('STARA ZAGORA', 'Stara Zagora'), ('PLEVEN', 'Pleven'), ('SLIVEN', 'Sliven'), ('DOBRICH', 'Dobrich'), ('SHUMEN', 'Shumen'), ('PERNIK', 'Pernik'), ('HASKOVO', 'Haskovo'), ('YAMBOL', 'Yambol'), ('Pazardzhik', 'Pazardzhik'), ('BLAGOEVGRAD', 'Blagoevgrad'), ('VELIKO TARNOVO', 'Veliko Tarnovo'), ('VIDIN', 'Vidin'), ('MONTANA', 'Montana'), ('LOVECH', 'Lovech'), ('RAZGRAD', 'Razgrad')], max_length=15),
        ),
    ]
