# Generated by Django 4.2.1 on 2023-08-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/property_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='landlord',
        ),
        migrations.AlterField(
            model_name='property',
            name='town',
            field=models.CharField(blank=True, choices=[('SOFIA', 'Sofia'), ('PLOVDIV', 'Plovdiv'), ('VARNA', 'Varna'), ('BURGAS', 'Burgas'), ('RUSE', 'Ruse'), ('STARA ZAGORA', 'Stara Zagora'), ('PLEVEN', 'Pleven'), ('SLIVEN', 'Sliven'), ('DOBRICH', 'Dobrich'), ('SHUMEN', 'Shumen'), ('PERNIK', 'Pernik'), ('HASKOVO', 'Haskovo'), ('YAMBOL', 'Yambol'), ('Pazardzhik', 'Pazardzhik'), ('BLAGOEVGRAD', 'Blagoevgrad'), ('VELIKO TARNOVO', 'Veliko Tarnovo'), ('VIDIN', 'Vidin'), ('MONTANA', 'Montana'), ('LOVECH', 'Lovech'), ('RAZGRAD', 'Razgrad')], default='SOFIA', max_length=15),
        ),
        migrations.AddField(
            model_name='property',
            name='pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.picture'),
        ),
    ]
