# Generated by Django 4.2.1 on 2023-08-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_furnished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='utilities_included',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='Yes', max_length=3, null=True),
        ),
    ]
