# Generated by Django 4.2.1 on 2023-08-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0045_remove_landlordprofile_properties_and_more'),
        ('properties', '0007_alter_property_utilities_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth_views.landlordprofile'),
        ),
        migrations.AddField(
            model_name='property',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, to='auth_views.profile'),
        ),
    ]
