# Generated by Django 4.2.1 on 2023-08-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0045_remove_landlordprofile_properties_and_more'),
        ('properties', '0008_property_landlord_property_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to='auth_views.profile'),
        ),
    ]
