# Generated by Django 4.2.1 on 2023-08-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0045_remove_landlordprofile_properties_and_more'),
        ('properties', '0011_remove_property_pictures_property_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='pictures',
        ),
        migrations.AddField(
            model_name='picture',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_views.profile'),
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='media/property_pics'),
        ),
    ]
