# Generated by Django 4.2.1 on 2023-08-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_landlord_remove_property_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
