# Generated by Django 4.2.1 on 2023-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_property_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
