# Generated by Django 4.2.1 on 2023-08-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0045_remove_landlordprofile_properties_and_more'),
        ('properties', '0017_property_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_views.landlordprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_views.profile')),
            ],
        ),
    ]
