# Generated by Django 4.2.1 on 2023-08-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='property',
            field=models.ManyToManyField(to='properties.property'),
        ),
    ]
