# Generated by Django 4.2.1 on 2023-08-07 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_messages_recipient_alter_messages_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='property',
        ),
        migrations.AddField(
            model_name='messages',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
