# Generated by Django 4.2.1 on 2023-08-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0045_remove_landlordprofile_properties_and_more'),
        ('properties', '0021_remove_messages_property_messages_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='MessageFromLandlord',
        ),
        migrations.AlterField(
            model_name='messagefromlandlord',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_views.profile'),
        ),
        migrations.AlterField(
            model_name='messagefromlandlord',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_views.landlordprofile'),
        ),
        migrations.CreateModel(
            name='MessageFromTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_views.landlordprofile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_views.profile')),
            ],
        ),
    ]
