# Generated by Django 4.2.1 on 2023-08-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_rename_messages_messagefromlandlord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='liked_by',
        ),
    ]
