# Generated by Django 4.2.1 on 2023-08-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_remove_property_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Studio', 'STUDIO'), ('Appartment', 'APPARTMENT'), ('Single Room', 'SINGLE ROOM')], default='ROOM', max_length=15),
        ),
    ]
