# Generated by Django 4.2.1 on 2023-08-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_views', '0048_alter_landlordprofile_location_and_more'),
        ('properties', '0026_property_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favourite',
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_views.profile')),
                ('property', models.ManyToManyField(to='properties.property')),
            ],
        ),
    ]
