CITIES = [
    ('---', '---'),
    ('SOF', 'Sofia'),
    ('VARNA', 'Varna'),
    ('Shumen', 'Shumen'),
    ('Burgas', 'Burgas'),
    ('Dobrich', 'Dobrich'),
    ('Ruse', 'Ruse'),
    ('Shumen', 'Shumen'),
    ('Veliko Tarnvovo', 'Veliko Tarnovo'),
    ('Stara Zagora', 'Stara Zagora'),
    ('Pleven', 'Pleven'),
    ('Lovech', 'Lovech'),
    ('Montana', 'Montana'),
    ('Gabrovo', 'Gabrovo'),
    ('Sliven', 'Sliven'),
    ('Vratsa', 'Vratsa'),
    ('Smolyan', 'Smolyan'),
    ('Targovishte', 'Targovishte'),
    ('Kardzali', 'Kardzali'),
    ('Pazardzhik', 'Pazardzhik'),
    ('Razgrad', 'Razgrad'),
    ('Yambol', 'Yambol'),
    ('Vidin', 'Vidin'),
    ('Blagoevgrad', 'Blagoevgrad'),
    ('Kyustendil', 'Kyustendil'),
    ('Sandanski', 'Sandanski'), 
    ('Asenovgrad', 'Asenovgrad'),
    ('Pernik', 'Pernik'),
    ('Nessebar', 'Nessebar'),
    ('Velingrad', 'Velingrad')
]
